dist: trusty
sudo: required
language: cpp


matrix:
  include:
    # OSX
    - os: osx
      osx_image: xcode8
      # env: PYVERSION=2
    # # Linux, Python3
    # - os: linux
    #   env: PYVERSION=3
    #   addons:
    #     apt:
    #       packages:
    #       - clang
    #       - ca-certificates
    #       - python3.6
    #       - python3-pip
    #       sources:
    #       - sourceline: 'ppa:ubuntu-toolchain-r/test'
    #       - sourceline: 'ppa:deadsnakes/ppa'
    # Linux, Python2
    - os: linux
      # env: PYVERSION=2
      addons:
        apt:
          packages:
          - clang
          - ca-certificates
          - python2.7
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:deadsnakes/ppa'

before_script:
  # Run homebrew on osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  # - shopt -s expand_aliases
  # - alias python=python$PYVERSION
  # - alias pip=pip$PYVERSION
  # pip install dependencies
  - sudo pip install twine enum34 setuptools toml

script:
  - clang --version
  - python --version
  - pip --version
  # test/hello
  - python setup.py install --user
  - clang-build -d"test/hello" -V
  - ./build/main
  # test/mini-project
  - clang-build -d"test/mini-project" -V
  - ./build/main
  # test/mwe-toml
  - clang-build -d"test/mwe-toml" -V
  - ./build/runHello
  # test/external-project
  - clang-build -d"test/external-project" -V
  - ./build/myexe/runHello
  # test/lib-and-exe
  - clang-build -d"test/lib-and-exe" -V
  # TODO: need to copy build/mylib/mylib.so into exe's directory on linux
  # - ./build/myexe/runLib