matrix:
  include:
    - language: python
      os: linux
      python: 3.6
      addons:
        apt:
          packages:
          - clang
          - ca-certificates
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:deadsnakes/ppa'
      dist: trusty

    - language: cpp
      os: osx
      osx_image: xcode8
      before_script:
        - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
  - pip install setuptools
  - python setup.py develop

script:
  - clang --version
  - python --version
  - pip --version
  # test/hello
  - clang-build -d"test/hello" -V
  - ./build/main
  # test/mini-project
  - clang-build -d"test/mini-project" -V
  - ./build/main
  # test/mwe-toml
  - clang-build -d"test/mwe-toml" -V
  - ./build/runHello
  # test/external-project
  - clang-build -d"test/external-project" -V
  - ./build/myexe/runHello
  # test/lib-and-exe
  - clang-build -d"test/lib-and-exe" -V
  # TODO: need to copy build/mylib/mylib.so into exe's directory on linux
  # - ./build/myexe/runLib