dist: trusty
language: python

os:
  - osx
    osx_image: xcode8
  - linux
    addons:
        apt:
          packages:
          - clang
          - ca-certificates
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:deadsnakes/ppa'

python:
  - '3.6'
  - '2.7'


before_install:
  # Run homebrew on osx
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install --with-clang llvm; else ; fi

install:
  - pip install setuptools

script:
  - clang --version
  - python --version
  - pip --version
  # test/hello
  - python setup.py develop
  - clang-build -d"test/hello" -V
  - ./build/main
  # test/mini-project
  - clang-build -d"test/mini-project" -V
  - ./build/main
  # test/mwe-toml
  - clang-build -d"test/mwe-toml" -V
  - ./build/runHello
  # test/external-project
  - clang-build -d"test/external-project" -V
  - ./build/myexe/runHello
  # test/lib-and-exe
  - clang-build -d"test/lib-and-exe" -V
  # TODO: need to copy build/mylib/mylib.so into exe's directory on linux
  # - ./build/myexe/runLib