env:
  global:
    - secure: "WDG1lYvH4eJUqtzX/+lA+CRRHuRdjLUvJQDb4OIQ8LhrTS2VNrFtjFOO2L4BPOothwoB7WMBd4Sgd5x4DHilvqYlj8O9Jfe2rBXZbZC73I9weCBezgJ1l2eM7fFkUrnhqW8QOXRI4ALE4bhSwW6y/CMOhkLW++xw0AVlWnF+gLa44V/dPBoaQODkS5Rn/k+vE4cwyyMBLFoTXvCKeyQQZBTZ5t3VV3QLR+gpcti+GfnkAkozBEjUpWGuafu4Z+rsqvvadErP/lihM0QjDxbKv5BXFTpts1ooSj0L4i9ga0qbNuD9sSGpj2TPV8qAomZqaoIsi9PCep4StcyuFhvPKt860WrIvCNi3yBG4N7DfH4rHruOHfDT7bUZtLWJ7qlVwdrs/qz7t0l6VpnInw1WoBFbC7Jbd0qFD/38AzkZ4UKHgh+Zp5gUPdOs5oLgHq59YEzkS/2Lv7dMU98BT5TpcqqJhvzBclW0xqUz3yabgw3rOpVfmiwoVSgtCJfkgJy7xJDd78Mr1JmWOT4/zkZBNTHDnfZtRGNfyEXOeohL6JrtRft1o/qKypsA2pi86H0bAM4j0KBBCpptgpckNvS2vdRUZlBWJRISp/sEEQdoT+u9YIDPpa8Kr1tzbdXLoIV4K+FIW3dvWSkVwL+IFpvQzcpKMWTHKXawzBai42Fccfo="
    - secure: "P748wDfVkSmcGGyWz1gtTGxhLQJ8fmE8K35DI55G71T2vXIhnanBUMUU3qF+wpYp3LqtJf3/LuEaoyi/K4wLoEdkkG4RR9HxyAaXWQONbWbEtwVUf5IySTfTvKniWgciA3f5BQCfBvjTWcO61skHOrwSc0IfVT09zYnL6GezztXPZC4V8I2cC24J4D/szFV3Z9WPPxpIKwUWK7s3f/nf+oZilVC/vwzNnwjMnK5xAcdZV12TfvhTht/735XkLQC7BSmni56oqiHFMO6hNLywUL2Jw9c4lCkNcUd5DAtda45Ht7ZmrUOl/ltGpfOrWT+ZX7lML9jI7VeqpnjZjV5tTEVbZKwEDedN/k1RiZ1byFC+nzE3I4tGm5FVlD52xbdtxwQjo20gC1t2BM4MHnfz6u8BUldLNvcsOi12AxOJjJc6kykis3oWMM0Ag5EGkzXfbpRNkJgYyURisbwWH7i8mluh8Y+4hkAaY9Pm8Fr2RyamxaVeW0vNkrxVRhTHKRQqZzSDFXNls5uQMH8aGNNy97YoUNzHGz7xVO6GyfqRkbOxb86HoFk8/+S0aa87K8QPgSyFq59zviIZnMZ278cM7lJatSjINr8OpyeZkdvNVHo6TJ8P0L7ZfvltL8jD+K2f3L2NdP4nyvFLvWYvfN0aPLBbziWwS4D5AgL2N2goZO8="

matrix:
  include:
    - language: python
      os: linux
      python: 3.6
      addons:
        apt:
          packages:
          - ca-certificates
          - libc++-dev
          - g++-7
          - clang
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:jonathonf/gcc-7.1'
          - sourceline: 'ppa:deadsnakes/ppa'
      dist: trusty
    - language: python
      os: linux
      python: 2.7
      addons:
        apt:
          packages:
          - ca-certificates
          - libc++-dev
          - g++-7
          - clang
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          - sourceline: 'ppa:jonathonf/gcc-7.1'
          - sourceline: 'ppa:deadsnakes/ppa'
      dist: trusty
    - language: cpp
      os: osx
      osx_image: xcode8
      before_script:
        - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
  - pip install setuptools
  - python setup.py develop

script:
  - clang --version
  - python --version
  - pip --version
  # test/hello
  - clang-build -d"test/hello" -V
  - ./build/main
  # test/mini-project
  - clang-build -d"test/mini-project" -V
  - ./build/main
  # test/mwe-toml
  - clang-build -d"test/mwe-toml" -V
  - ./build/runHello
  # test/external-project
  - clang-build -d"test/external-project" -V
  - ./build/myexe/runHello
  # test/lib-and-exe
  - clang-build -d"test/lib-and-exe" -V
  # TODO: need to copy build/mylib/mylib.so into exe's directory on linux
  # - ./build/myexe/runLib

deploy:
  provider: pypi
  user:     "$PYPIUSER"
  password: "$PYPIPASSWORD"
  on:
    all_branches: true